# "service" is the name of this project. This will also be added to your AWS resource names.
service: notes-service
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NOTES_TABLE_NAME: !Ref NotesTable

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [NotesTable, Arn]

functions:
  createNote:
    name: createNote
    description: This function creates a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.createNote
    events:
      - httpApi:
          method: POST
          path: /notes
  updateNote:
    name: updateNote
    description: This function update a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.updateNote
    events:
      - httpApi:
          method: PUT
          path: /notes/{id}

  deleteNote:
    name: deleteNote
    description: This function delete a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.deleteNote
    events:
      - httpApi:
          method: DELETE
          path: /notes/{id}

  fetchNoteById:
    name: fetchNoteById
    description: This function fetch a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.fetchNoteById  
    events:
      - httpApi:
          method: GET
          path: /notes/{id}
  fetchNotes:
    name: fetchNotes
    description: This function fetch all note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.fetchNotes
    events:
      - httpApi:
          method: GET
          path: /notes

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-table-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

