# "service" is the name of this project. This will also be added to your AWS resource names.
service: notes-service
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    usagePlan:
      throttle:
        burstLimit: 10
        rateLimit: 50
      quota:
        limit: 10000
        period: DAY
        offset: 0
    apiKeys:
      - name: api-key-${self:provider.stage}
        value: super-secret-api-key
  environment:
    NOTES_TABLE_NAME: !Ref NotesTable
    COGNITO_USERPOOL_ID: !Ref CognitoUserPool
    COGNITO__WEBCLIENT_ID: !Ref CognitoUserPoolWebclient

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [NotesTable, Arn]

functions:
  authorizer:
    name: authorizer
    description: This function authorizes the request
    handler: src/functions/authorizer.handler
  createNote:
    name: createNote
    description: This function creates a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.createNote
    events:
      - http:
          method: POST
          path: /notes
          cors: true
          authorizer: authorizer
  updateNote:
    name: updateNote
    description: This function update a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.updateNote
    events:
      - http:
          method: PUT
          path: /notes/{id}
          cors: true
          authorizer: authorizer

  deleteNote:
    name: deleteNote
    description: This function delete a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.deleteNote
    events:
      - http:
          method: DELETE
          path: /notes/{id}
          cors: true
          authorizer: authorizer

  fetchNoteById:
    name: fetchNoteById
    description: This function fetch a note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.fetchNoteById  
    events:
      - http:
          method: GET
          path: /notes/{id}
          cors: true
          authorizer: authorizer
  fetchNotes:
    name: fetchNotes
    description: This function fetch all note in the Note Table in DynamoDB
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5
    handler: src/functions/api/handler.fetchNotes
    events:
      - http:
          method: GET
          path: /notes
          cors: true
          authorizer: 
            name: userpool_auth
            arn: !GetAtt CognitoUserPool.Arn
            

resources:
  Resources:
    ${file(resources.yml)}